'use client';
import {useEffect,useRef,useState} from 'react';
export default function CloudLibrary(){
 const [items,setItems]=useState([]),[selected,setSelected]=useState([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[playing,setPlaying]=useState(null);const input=useRef(null);
 async function load(){try{const r=await fetch('/api/cloud-videos',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'Falha ao carregar');setItems(d.videos||[])}catch(e){setMessage(e.message)}}
 useEffect(()=>{load()},[]);
 async function upload(files){if(!files?.length)return;setBusy(true);let done=0;try{for(const file of Array.from(files)){const form=new FormData();form.set('file',file);const r=await fetch('/api/cloud-videos',{method:'POST',body:form});const d=await r.json();if(!r.ok)throw Error(d.error||'Falha ao enviar');done++}setMessage(done+' vídeo(s) salvos na nuvem.');await load()}catch(e){setMessage(e.message+' ('+done+' enviados).');await load()}finally{setBusy(false);if(input.current)input.current.value=''}}
 async function remove(ids){if(!ids.length||!confirm('Excluir '+ids.length+' vídeo(s) permanentemente da nuvem?'))return;setBusy(true);try{const r=await fetch('/api/cloud-videos/remove',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids})});const d=await r.json();if(!r.ok)throw Error(d.error||'Falha ao excluir');setPlaying(null);setSelected([]);await load();setMessage('Vídeos excluídos da nuvem.')}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 return <section className="videoPanel"><div className="libraryHeading"><h2>Biblioteca na nuvem ({items.length})</h2><span>Armazenamento privado</span></div><p>Os vídeos desta área ficam na Vercel e podem ser vistos sem salvar MP4 no computador. Os novos downloads automáticos serão conectados aqui.</p><input ref={input} type="file" multiple accept="video/mp4" disabled={busy} onChange={e=>upload(e.target.files)} aria-label="Enviar vídeos MP4 para nuvem"/><p className="helper">Envio manual de teste: até 4 MB por vídeo. O importador automático continuará sendo preparado para arquivos maiores.</p>{message&&<p className="videoNotice" role="status">{message}</p>}{items.length>0&&<><div className="reviewTools"><button type="button" onClick={()=>setSelected(items.map(x=>x.id))}>Selecionar todos</button><button type="button" onClick={()=>setSelected([])}>Limpar seleção</button><button type="button" disabled={busy||!selected.length} className="dangerAction" onClick={()=>remove(selected)}>Excluir ({selected.length})</button><button type="button" onClick={load}>Atualizar</button></div><div className="reviewGrid">{items.map(v=><article key={v.id} className="reviewCard"><div className="reviewVisual" onClick={()=>setPlaying(v)} role="button" tabIndex={0} onKeyDown={e=>e.key==='Enter'&&setPlaying(v)}><span className="reviewPlay">▶</span><span className="reviewHint">Assistir no Studio</span></div><div className="reviewInfo"><label className="selectVideo"><input type="checkbox" checked={selected.includes(v.id)} onChange={()=>setSelected(s=>s.includes(v.id)?s.filter(x=>x!==v.id):[...s,v.id])}/><span>{v.name}</span></label><small>{(v.size/1048576).toFixed(1)} MB</small><div className="videoItemActions"><button onClick={()=>setPlaying(v)}>Assistir</button><button onClick={()=>remove([v.id])}>Excluir</button></div></div></article>)}</div></>}{playing&&<div className="previewOverlay" role="dialog" aria-modal="true" aria-label="Assistir vídeo"><div className="previewDialog"><div className="previewHeading"><strong>{playing.name}</strong><button onClick={()=>setPlaying(null)}>✕</button></div><video controls playsInline autoPlay src={'/api/cloud-videos/media?pathname='+encodeURIComponent(playing.pathname)} className="previewPlayer"/><div className="previewFooter"><button onClick={()=>setPlaying(null)}>Fechar</button></div></div></div>}</section>
}