'use client';
import {useEffect,useRef,useState} from 'react';

const DB_NAME='nfc-studio-videos-v1';
const STORE='videos';
const PROFILE_KEY='nfc-studio-tiktok-profile';
function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:'id'});};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function storeAction(mode,value){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,mode==='list'?'readonly':'readwrite');const st=tx.objectStore(STORE);let req;if(mode==='list')req=st.getAll();if(mode==='save')req=st.put(value);if(mode==='delete')req=st.delete(value);tx.oncomplete=()=>{db.close();resolve(req?.result)};tx.onerror=()=>{db.close();reject(tx.error)};});}
function validateProfile(url){try{const x=new URL(url);return (x.protocol==='https:'||x.protocol==='http:')&&['tiktok.com','www.tiktok.com','m.tiktok.com'].includes(x.hostname)&&/^\/@[A-Za-z0-9._-]+\/?$/.test(x.pathname)}catch{return false}}
function fileName(x){return x.name.length>58?x.name.slice(0,55)+'…':x.name;}
export default function VideoLibrary(){
 const [profile,setProfile]=useState('');const [records,setRecords]=useState([]);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [importCount,setImportCount]=useState(3);const [importRuns,setImportRuns]=useState([]);const [importBusy,setImportBusy]=useState(false);const [preview,setPreview]=useState(null);const [previewUrl,setPreviewUrl]=useState('');const [selected,setSelected]=useState([]);const input=useRef(null);
 async function refresh(){try{const r=await storeAction('list');setRecords(r.sort((a,b)=>b.added-a.added).map(({blob,...meta})=>meta))}catch{setNotice('Armazenamento indisponível neste navegador. Tente outro navegador atualizado.');}}
 useEffect(()=>{setProfile(localStorage.getItem(PROFILE_KEY)||'');refresh()},[]);
 function saveProfile(){if(profile.trim()&&!validateProfile(profile.trim())){setNotice('Informe um perfil válido, por exemplo https://www.tiktok.com/@usuario');return;}localStorage.setItem(PROFILE_KEY,profile.trim());setNotice('Perfil salvo neste aparelho. A importação direta do TikTok ainda não está habilitada.');}
 async function checkImports(){try{const response=await fetch('/api/tiktok-import/status',{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'Falha ao consultar');setImportRuns(data.runs||[]);setNotice('Histórico de importações atualizado.');}catch(e){setNotice(e.message)}}
 async function startImport(){if(!validateProfile(profile)){setNotice('Informe antes um link de perfil TikTok válido.');return;}if(!confirm('Iniciar a importação de '+importCount+' vídeo(s) de um perfil cujo uso foi autorizado?'))return;setImportBusy(true);try{const response=await fetch('/api/tiktok-import/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile,count:importCount})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Falha ao iniciar');setNotice(data.message);await checkImports()}catch(e){setNotice(e.message)}finally{setImportBusy(false)}}
 async function syncRun(runId){setImportBusy(true);try{setNotice('Transferindo vídeos para a biblioteca privada na nuvem...');const response=await fetch('/api/tiktok-import/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({runId})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Falha na sincronização');setNotice(result.message+(result.skipped?.length?' '+result.skipped.length+' ignorado(s).':''));window.dispatchEvent(new Event('studio:cloud-updated'));}catch(e){setNotice(e.message)}finally{setImportBusy(false)}}
 async function addFiles(files){const accepted=Array.from(files).filter(f=>['video/mp4','video/quicktime','video/webm'].includes(f.type)||/\.(mp4|mov|webm)$/i.test(f.name));if(!accepted.length){setNotice('Selecione vídeos MP4, MOV ou WEBM.');return}if(records.length+accepted.length>100){setNotice('Limite inicial de 100 vídeos por biblioteca. Exclua alguns antes de importar mais.');return}setBusy(true);let count=0;try{for(const f of accepted){await storeAction('save',{id:crypto.randomUUID(),name:f.name,type:f.type||'video/mp4',size:f.size,added:Date.now(),profile:profile.trim(),blob:f});count++;}await refresh();setNotice(count+' vídeo(s) guardado(s) neste navegador.');}catch(e){setNotice('Não foi possível guardar todos os vídeos. Confira o espaço disponível no aparelho.');await refresh()}finally{setBusy(false);if(input.current)input.current.value='';}}
 async function download(record){try{const db=await openDb();const item=await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly');const req=tx.objectStore(STORE).get(record.id);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});db.close();if(!item?.blob)return;const url=URL.createObjectURL(item.blob);const a=document.createElement('a');a.href=url;a.download=item.name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}catch{setNotice('Não foi possível baixar o arquivo.');}}
 async function remove(id){if(!confirm('Excluir este vídeo da biblioteca neste aparelho?'))return;await storeAction('delete',id);setSelected(s=>s.filter(x=>x!==id));if(preview?.id===id)closePreview();await refresh();}
 async function showPreview(record){try{closePreview();const db=await openDb();const item=await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly');const req=tx.objectStore(STORE).get(record.id);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});db.close();if(!item?.blob)throw Error('Arquivo não encontrado');const url=URL.createObjectURL(item.blob);setPreview(record);setPreviewUrl(url)}catch{setNotice('Não foi possível reproduzir o vídeo. Confira o formato do arquivo.');}}
 function closePreview(){setPreview(null);setPreviewUrl('');}
 function toggleSelect(id){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);}
 async function removeSelected(){if(!selected.length||!confirm('Excluir '+selected.length+' vídeo(s) selecionado(s) deste navegador?'))return;setBusy(true);try{for(const id of selected)await storeAction('delete',id);setSelected([]);closePreview();await refresh();setNotice('Vídeos selecionados excluídos.')}finally{setBusy(false);}}

 return <div className="dashMain"><div className="eyebrow">BIBLIOTECA DE VÍDEOS</div><h1>Importar <span>vídeos.</span></h1><p className="muted">Cadastre o perfil de origem e organize arquivos que você possui ou está autorizado a reutilizar.</p>
 <section className="videoPanel"><h2>1. Perfil TikTok de origem</h2><label className="fieldLabel" htmlFor="profile">Link do perfil</label><div className="videoActions"><input id="profile" value={profile} onChange={e=>setProfile(e.target.value)} placeholder="https://www.tiktok.com/@usuario" type="url"/><button onClick={saveProfile} className="primaryAction">Salvar perfil</button></div>{validateProfile(profile)&&<a className="textLink" href={profile} target="_blank" rel="noreferrer">Abrir perfil no TikTok ↗</a>}<p className="helper">O link fica cadastrado para identificar a origem. O download automático de perfis ainda não está disponível; não usamos extração não autorizada.</p></section>
 <section className="videoPanel"><h2>2. Importação automática (experimental)</h2><p>Importe vídeos de um perfil autorizado utilizando um processamento separado no GitHub. Comece com 3 vídeos para validar o resultado.</p><div className="videoActions"><label htmlFor="count" className="fieldLabel">Quantidade (1 a 100)</label><input id="count" type="number" min="1" max="100" value={importCount} onChange={e=>setImportCount(Math.min(100,Math.max(1,Number(e.target.value)||1)))}/><button className="primaryAction" type="button" disabled={importBusy} onClick={startImport}>{importBusy?'Iniciando...':'Iniciar importação'}</button></div><div className="reviewTools"><button type="button" onClick={checkImports}>Atualizar andamento</button></div>{importRuns.length>0&&<div className="videoList">{importRuns.map(run=><div className="videoItem" key={run.id}><div><strong>{run.status==='completed'?(run.conclusion==='success'?'Processamento concluído':'Processamento com falha'):'Processando / aguardando fila'}</strong><small>{new Date(run.created).toLocaleString('pt-BR')}</small></div><div className="videoItemActions">{run.status==="completed"&&run.conclusion==="success"&&<button disabled={importBusy} className="primaryAction" type="button" onClick={()=>syncRun(run.id)}>Enviar vídeos para nuvem</button>}<a className="textLink" href={run.url} rel="noreferrer" target="_blank">Ver detalhes ↗</a></div></div>)}</div>}<p className="helper">Quando a execução terminar, toque em “Enviar vídeos para nuvem”. A transferência acontece entre servidores, sem salvar arquivos no seu computador. Nesta primeira versão, pacotes acima de 25 MB precisam ser divididos em lotes menores.</p></section>
 <section className="videoPanel"><h2>3. Importar arquivos para revisão</h2><p>Selecione até 100 vídeos MP4, MOV ou WEBM de uma vez. Os arquivos serão mantidos no armazenamento deste navegador.</p><input ref={input} aria-label="Selecionar vídeos" type="file" accept="video/mp4,video/quicktime,video/webm,.mp4,.mov,.webm" multiple onChange={e=>addFiles(e.target.files)} disabled={busy}/><p className="helper">Importante: estes vídeos NÃO são enviados para a nuvem e NÃO serão sincronizados entre celular e computador. Evite apagar os dados do navegador.</p></section>
 {notice&&<p role="status" className="videoNotice">{notice}</p>}
 <section className="videoPanel"><div className="libraryHeading"><h2>4. Revisar biblioteca ({records.length}/100)</h2><span>{selected.length} selecionado(s)</span></div>{records.length===0?<p>Nenhum vídeo importado ainda.</p>:<><div className="reviewTools"><button type="button" onClick={()=>setSelected(records.map(x=>x.id))}>Selecionar todos</button><button type="button" onClick={()=>setSelected([])}>Limpar seleção</button><button type="button" className="dangerAction" disabled={!selected.length||busy} onClick={removeSelected}>Excluir selecionados ({selected.length})</button></div><div className="reviewGrid">{records.map(record=><article className="reviewCard" key={record.id}><div className="reviewVisual" role="button" tabIndex={0} onClick={()=>showPreview(record)} onKeyDown={e=>{if(e.key==='Enter')showPreview(record)}}><span className="reviewPlay">▶</span><span className="reviewHint">Ver vídeo</span></div><div className="reviewInfo"><label className="selectVideo"><input type="checkbox" checked={selected.includes(record.id)} onChange={()=>toggleSelect(record.id)}/><span title={record.name}>{fileName(record)}</span></label><small>{(record.size/1048576).toFixed(1)} MB · {new Date(record.added).toLocaleDateString('pt-BR')}</small><div className="videoItemActions"><button onClick={()=>showPreview(record)}>Assistir</button><button onClick={()=>download(record)}>Baixar</button><button className="dangerAction" onClick={()=>remove(record.id)}>Excluir</button></div></div></article>)}</div></>}</section>
 {preview&&<div className="previewOverlay" role="dialog" aria-modal="true" aria-label="Prévia de vídeo"><div className="previewDialog"><div className="previewHeading"><strong>{preview.name}</strong><button aria-label="Fechar prévia" onClick={closePreview}>✕</button></div><video key={previewUrl} src={previewUrl} controls playsInline autoPlay className="previewPlayer" onError={()=>setNotice('Este navegador não conseguiu reproduzir o formato do vídeo.')}/><div className="previewFooter"><button onClick={()=>download(preview)}>Baixar vídeo</button><button onClick={closePreview}>Voltar à lista</button></div></div></div>}
 <p className="notice">Próxima etapa: importar vídeos diretamente de fontes autorizadas com armazenamento seguro na nuvem, para acessar de qualquer aparelho.</p></div>
}
